# Generated by Django 5.0.6 on 2024-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名字', models.CharField(max_length=200)),
                ('留言', models.CharField(max_length=1000)),
            ],
        ),
    ]
